### ISSUE TITLE
hi. i run this on colab. but error occured.

### ISSUE THREAD

**Issue by bamtu** [tsugumi-sys/SA-ConvLSTM-Pytorch#21]
error is 

Training Self Attention (Memory) ConvLSTM...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/pipeline/moving_mnist/self_attention_memory_convlstm.py", line 96, in <module>
    main()
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/pipeline/moving_mnist/self_attention_memory_convlstm.py", line 81, in main
    trainer.run()
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/pipeline/trainer.py", line 39, in run
    results = self.train()
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/pipeline/trainer.py", line 48, in train
    output = self.model(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/self_attention_memory_convlstm/seq2seq.py", line 93, in forward
    output = self.sequential(X)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/self_attention_memory_convlstm/model.py", line 76, in forward
    h, cell, memory, attention_h = self.sam_convlstm_cell(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/self_attention_memory_convlstm/cell.py", line 43, in forward
    new_h, new_cell = self.convlstm_cell(X, prev_h, prev_cell)
  File "/content/drive/MyDrive/Colab Notebooks/SA-Pytorch/core/convlstm_cell.py", line 94, in convlstm_cell
    conv_output = self.conv(torch.cat([X, prev_h], dim=1))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat)

**Comment by tsugumi-sys** [comment]
@bamtu 
Thank you for reporting this issue :)
I fixed this error and checked the latest code works on colab (testing with ConvLSTM).

![image](https://github.com/tsugumi-sys/SA-ConvLSTM-Pytorch/assets/61897166/3702cb21-e73e-4731-bce5-88e69352fc56)
