### ISSUE TITLE
error in evaluation.

### ISSUE THREAD

**Issue by bamtu** [tsugumi-sys/SA-ConvLSTM-Pytorch#41]
error : 

Validation loss decreased (inf --> 3646.218018). Saving model ...
Evaluating ...
torch.Size([1, 1, 10, 64, 64])
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\JD\Downloads\SA-ConvLSTM-Pytorch-main (3)\SA-ConvLSTM-Pytorch-main\pipelines\moving_mnist_pipeline\self_attention_memory_convlstm.py", line 100, in <module>
    main()
  File "C:\Users\JD\Downloads\SA-ConvLSTM-Pytorch-main (3)\SA-ConvLSTM-Pytorch-main\pipelines\moving_mnist_pipeline\self_attention_memory_convlstm.py", line 96, in main
    evaluator.run()
  File "C:\Users\JD\Downloads\SA-ConvLSTM-Pytorch-main (3)\SA-ConvLSTM-Pytorch-main\pipelines\evaluator.py", line 34, in run
    self.visualize_predlabel_frames(batch_idx, label, pred_frames)
  File "C:\Users\JD\Downloads\SA-ConvLSTM-Pytorch-main (3)\SA-ConvLSTM-Pytorch-main\pipelines\evaluator.py", line 56, in visualize_predlabel_frames
    ax.imshow(frame_data[0, 0, fidx], cmap="gray")
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\axes\_axes.py", line 5663, in imshow
    im.set_data(X)
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\image.py", line 697, in set_data
    self._A = cbook.safe_masked_invalid(A, copy=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\matplotlib\cbook\__init__.py", line 714, in safe_masked_invalid
    x = np.array(x, subok=True, copy=copy)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JD\AppData\Roaming\Python\Python311\site-packages\torch\_tensor.py", line 1030, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Thank you.

**Comment by tsugumi-sys** [comment]
@bamtu 
Thank you for reporting this issue :)
I think this issue has been fixed by #42 .
Please check in your environment.
